### ISSUE TITLE
Could not send feature report (ioctl (SFEATURE): Broken pipe)

### ISSUE THREAD

**Issue by belegdol** [raphnet/gcn64tools#11]
Hello,

I tried updating the firmware on my Saturn adapter (289b:0043). It failed. In the console I can see the following when trying to reset the adapter:
```
$ ./gcn64ctl_gui -s

(gcn64ctl_gui:92489): Gtk-CRITICAL **: 17:01:05.430: gtk_combo_box_set_row_span_column: assertion 'row_span >= -1 && row_span < col' failed
Listing device...
Start listing
Considering 0x289b:0x0043
Considering 0x289b:0x0043
Considering 0x289b:0x0043
Device 'Saturn to USB v3.0'
/dev/hidraw7
Opening device path: '/dev/hidraw7'
Current mapping: 0x30
Adapter signature: bffd5a12-8cb9-4c40-8a7a-8b423dcaa7aa
poll interval: 5
Value: 5
send feature report: retry
send feature report: retry
Could not send feature report (ioctl (SFEATURE): Przerwany potok)
Error sending command
deselect adapter
Listing device...
Start listing
Considering 0x289b:0x0043
Considering 0x289b:0x0043
Considering 0x289b:0x0043
Device 'Saturn to USB v3.0'
/dev/hidraw7
Opening device path: '/dev/hidraw7'
Current mapping: 0x30
Adapter signature: bffd5a12-8cb9-4c40-8a7a-8b423dcaa7aa
poll interval: 5
Current mapping: 0x30
Adapter signature: bffd5a12-8cb9-4c40-8a7a-8b423dcaa7aa
poll interval: 5
```

**Comment by raphnet** [comment]
Hello!

Instead of gcn64ctl_gui, could you try listing the adapter with `gcn64ctl -l` and then, `./gcn64ctl -f --get_version` ?

**Comment by belegdol** [comment]
Sure:
```
$ ./gcn64ctl -l
Simply listing the devices...
Found device 'Saturn to USB v3.0', serial '100184'. Supports 1 channel(s), 0 raw channel(s), Block io: No
1 device(s) found
Found 1 devices
$ ./gcn64ctl -f --get_version
Will use device 'Saturn to USB v3.0' serial '100184'
Firmware version: 3.0.1
```

**Comment by raphnet** [comment]
Ok, so the adapter still has a firmware, which suggest that even the first step (erasing the firmware) did not complete.

Do you have dfu-programmer in your path, with appropriate permissions (as in scripts/10-atmel-dfu.rules) for direct access to the device when it is in DFU mode?

If this is the case and it still does not work, please look for a file called raphnetupdatelog.txt in your home directory, it should contain more details.

**Comment by belegdol** [comment]
I was actually missing dfu-programmer. Having said that, even with it installed, the upgrade did not work:
[raphnetupdatelog.txt](https://github.com/raphnet/gcn64tools/files/7584169/raphnetupdatelog.txt)
```
2021-11-22T20:31:06.922055Z: [dfu-update message] : dfu-programmer: no device present.
2021-11-22T20:31:06.922384Z: [dfu-update message] : dfu-programmer: no device present.
```
 I have udev rules installed:
```
$ ls /etc/udev/rules.d/ -l
razem 20
-rw-r--r--. 1 root root   166 2019-11-06  10-atmel-dfu.rules
-rw-r--r--. 1 root root 13661 11-20 16:51 10-raphnet.rules
```
Looking closer, something seems not right:
```
lis 22 21:26:52 napoleon2 systemd-udevd[734]: /etc/udev/rules.d/10-atmel-dfu.rules:1 Invalid key/value pair, ignoring.
lis 22 21:26:52 napoleon2 systemd-udevd[734]: /etc/udev/rules.d/10-atmel-dfu.rules:2 Invalid key/value pair, ignoring.
```

**Comment by belegdol** [comment]
I deleted the comments from the udev file and update has succeeded. Looks like putting a comment after a # at the end of the line is no longer allowed.

**Comment by raphnet** [comment]
Thank you, this will be fixed in the next release
