### ISSUE TITLE
PS1/PS2 to USB converter

### ISSUE THREAD

**Issue by badass-boss** [raphnet/gcn64tools#13]
You have so many repositories for so many sorts of converters, including NES/SNES to USB, N64/GC to USB, Saturn to USB and even Jaguar to USB or VirtualBoy to USB (but why???) which is so good. This repository has everything BUT PS1 to USB converter for some reason or at least I didn't find it... Will you be releasing PS1/PS2 to USB converter as well?? Looking forward for a professional product or code for this as well!

**Comment by raphnet** [comment]
As for a professional product, I designed this PS1/PS2 to USB converter:
https://www.raphnet-tech.com/products/psx_to_usb/index.php

However at this time there is no open source code release for it.
